# Connection parameters for MongoDB.
#
mongodb_connection_string: "mongodb://localhost:27017"
mongodb_database_name: "uae_currency_rates"
mongodb_max_delay: 5

# Indicates currencies to work with. If it has no items, it means that
# it includes all possible currencies the crawler is able to find.
#
# Example:
# - USD
# - EUR
#
currency_codes_filter:
  - USD
  - EUR

# This options defines how many days (including the current one)
# must be retrieved each time when crawler begins to load
# current currency rates.
#
# For instance: today is 2022-10-17, days_to_check is 3. Having this,
# the crawler will get rates for:
# - 2022-10-17
# - 2022-10-16
# - 2022-10-15
#
days_to_check: 7

# Logging configuration.
#
# Details are here (in case you need them):
# https://docs.python.org/3/library/logging.config.html
#
load_current_logging:

  version: 1

  disable_existing_loggers: true

  formatters:
    json:
      format: '%(asctime)s [%(levelname)s] %(message)s'

  handlers:

    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: json
      stream: ext://sys.stdout

  loggers:

    crawler:
      level: DEBUG
      handlers: [console]
      propagate: no

  root:
    level: DEBUG
    handlers: [console]

load_history_logging:

  version: 1

  disable_existing_loggers: true

  formatters:
    json:
      format: '%(asctime)s [%(levelname)s] %(message)s'

  handlers:

    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: json
      stream: ext://sys.stdout

  loggers:

    crawler:
      level: DEBUG
      handlers: [console]
      propagate: no

  root:
    level: DEBUG
    handlers: [console]

api_logging:

  version: 1

  disable_existing_loggers: true

  formatters:
    json:
      format: '%(asctime)s [%(levelname)s] %(message)s'

  handlers:

    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: json
      stream: ext://sys.stdout

  loggers:

    crawler:
      level: DEBUG
      handlers: [console]
      propagate: no

  root:
    level: DEBUG
    handlers: [console]

# External URL of the REST service will be added to log entries
# and messages to the Telegram chat specified in telegram_chat_id.
#
# A purpose of the feature is debugging, so you may leave it blank.
#
api_url: ""

# Lifespan of the current rates loading event in seconds. If no event
# appears after limit is reached, heartbeat warns you.
#
# The default value is 5400 (1 hour 30 minutes).
#
heartbeat_current_rates_loading_event_lifespan: 5400

# Lifespan of the current rates updating event in seconds. If no event
# appears after limit is reached, heartbeat warns you.
#
# The default value is 432000 (5 days).
#
heartbeat_current_rates_updating_event_lifespan: 432000

# Lifespan of the current rates availability event in seconds. If no event
# appears after limit is reached, heartbeat warns you.
#
# The default value is 21600 (6 hours).
#
heartbeat_current_rates_availability_event_lifespan: 21600

# Lifespan of the historical rates loading event in seconds. If no event
# appears after limit is reached, heartbeat warns you.
#
# The default value is 129600 (1 day 12 hours).
#
heartbeat_historical_rates_loading_event_lifespan: 129600

# A value of the User-Agent HTTP header that crawler will use
# making requests to the bank website.
#
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"

# Integration parameters for Telegram.
#
# Fill the fields below if you want to see a summary of imported currency rates
# in the specified Telegram chat.
#
telegram_bot_api_token: ""
telegram_chat_id: ""

# Currency codes (in Arabic & English). This list is intended to convert
# a presentation of a currency to its code, accordingly to ISO 4217.
#
# Currently, the bank's website returns currency titles in Arabic. However,
# in some cases you still can get English ones, so I included them as well.
#
currency_codes:
  "دولار امريكي": USD
  "بيسو ارجنتيني": ARS
  "دولار استرالي": AUD
  "تاكا بنغلاديشية": BDT
  "دينار بحريني": BHD
  "دولار بروناي": BND
  "ريال برازيلي": BRL
  "بولا بوتسواني": BWP
  "روبل بلاروسي": BYN
  "دولار كندي": CAD
  "فرنك سويسري": CHF
  "بيزو تشيلي": CLP
  "يوان صيني - الخارج": CNY
  "يوان صيني": CNY
  "بيزو كولومبي": COP
  "كرونة تشيكية": CZK
  "كرون دانماركي": DKK
  "دينار جزائري": DZD
  "جينيه مصري": EGP
  "يورو": EUR
  "جنيه استرليني": GBP
  "دولار هونج كونج": HKD
  "فورنت هنغاري": HUF
  "روبية اندونيسية": IDR
  "روبية هندية": INR
  "كرونة آيسلندية": ISK
  "دينار أردني": JOD
  "ين ياباني": JPY
  "شلن كيني": KES
  "ون كوري": KRW
  "دينار كويتي": KWD
  "تينغ كازاخستاني": KZT
  "ليرة لبنانية": LBP
  "روبية سريلانكي": LKR
  "درهم مغربي": MAD
  "دينار مقدوني": MKD
  "بيسو مكسيكي": MXN
  "رينغيت ماليزي": MYR
  "نيرا نيجيري": NGN
  "كرون نرويجي": NOK
  "دولار نيوزيلندي": NZD
  "ريال عماني": OMR
  "سول بيروفي": PEN
  "بيسو فلبيني": PHP
  "روبية باكستانية": PKR
  "زلوتي بولندي": PLN
  "ريال قطري": QAR
  "دينار صربي": RSD
  "روبل روسي": RUB
  "ريال سعودي": SAR
  "دينار سوداني": SDG
  "كرونة سويدية": SWK
  "دولار سنغافوري": SGD
  "بات تايلندي": THB
  "دينار تونسي": TND
  "ليرة تركية": TRY
  "دولار تريندادي": TTD
  "دولار تايواني": TWD
  "شلن تنزاني": TZS
  "شلن اوغندي": UGX
  "دونغ فيتنامي": VND
  "ريال يمني": YER
  "راند جنوب أفريقي": ZAR
  "كواشا زامبي": ZMW
  "مانات أذربيجاني": AZN
  "ليف بلغاري": BGN
  "كونا كرواتية": HRK
  "بر إثيوبي": ETB
  "دينار عراقي": IQD
  "شيكل اسرائيلي": ILS
  "دينار ليبي": LYD
  "روبي موريشي": MUR
  "ليو روماني": RON
  "ليرة سورية": SYP
  "منات تركمانستاني": TMT
  "سوم أوزبكستاني": UZS
  "New Zealand Dollar": NZD
  "US Dollar": USD
  "Argentine Peso": ARS
  "Australian Dollar": AUD
  "Bangladesh Taka": BDT
  "Bahrani Dinar": BHD
  "Brunei Dollar": BND
  "Brazilian Real": BRL
  "Botswana Pula": BWP
  "Belarus Rouble": BYN
  "Canadian Dollar": CAD
  "Swiss Franc": CHF
  "Chilean Peso": CLP
  "Chinese Yuan - Offshore": CNY
  "Chinese Yuan": CNY
  "Colombian Peso": COP
  "Czech Koruna": CZK
  "Danish Krone": DKK
  "Algerian Dinar": DZD
  "Egypt Pound": EGP
  "Euro": EUR
  "GB Pound": GBP
  "Hongkong Dollar": HKD
  "Hungarian Forint": HUF
  "Indonesia Rupiah": IDR
  "Indian Rupee": INR
  "Iceland Krona": ISK
  "Jordan Dinar": JOD
  "Japanese Yen": JPY
  "Kenya Shilling": KES
  "Korean Won": KRW
  "Kuwaiti Dinar": KWD
  "Kazakhstan Tenge": KZT
  "Lebanon Pound": LBP
  "Sri Lanka Rupee": LKR
  "Moroccan Dirham": MAD
  "Macedonia Denar": MKD
  "Mexican Peso": MXN
  "Malaysia Ringgit": MYR
  "Nigerian Naira": NGN
  "Norwegian Krone": NOK
  "NewZealand Dollar": NZD
  "Omani Rial": OMR
  "Peru Sol": PEN
  "Philippine Piso": PHP
  "Pakistan Rupee": PKR
  "Polish Zloty": PLN
  "Qatari Riyal": QAR
  "Serbian Dinar": RSD
  "Russia Rouble": RUB
  "Saudi Riyal": SAR
  "Swedish Krona": SWK
  "Singapore Dollar": SGD
  "Thai Baht": THB
  "Tunisian Dinar": TND
  "Turkish Lira": TRY
  "Trin Tob Dollar": TTD
  "Taiwan Dollar": TWD
  "Tanzania Shilling": TZS
  "Uganda Shilling": UGX
  "Vietnam Dong": VND
  "South Africa Rand": ZAR
  "Zambian Kwacha": ZMW
  "Sudanese Pound": SDG
  "Yemen Rial": YER
  "Azerbaijan manat": AZN
  "Bulgarian lev": BGN
  "Croatian kuna": HRK
  "Ethiopian birr": ETB
  "Iraqi dinar": IQD
  "Israeli new shekel": ILS
  "Libyan dinar": LYD
  "Mauritian rupee": MUR
  "Romanian leu": RON
  "Syrian pound": SYP
  "Turkmen manat": TMT
  "Uzbekistani som": UZS
